# Generated by Django 3.2.3 on 2021-05-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210518_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupname',
            old_name='name',
            new_name='group_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Web Admin', 'Web Admin'), ('Group Admin', 'Group Admin')], default='User', max_length=100, null=True),
        ),
    ]
