# Generated by Django 3.2.3 on 2021-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_groupname_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='group_name',
            field=models.CharField(error_messages={'unique': 'Error while creating the account. A shop with that name already exists.'}, max_length=100, unique=True),
        ),
    ]
