# Generated by Django 3.2.3 on 2021-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_groupname_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/profile_images/avatar.png', upload_to='profile_images'),
        ),
    ]
