# Generated by Django 3.2.3 on 2021-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='product',
            name='total_sale',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
