# Generated by Django 3.2.3 on 2021-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210519_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
