# Generated by Django 3.2.3 on 2021-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'Error while creating'}, max_length=100, null=True, unique=True),
        ),
    ]
